export const AI_CONFIG = {
  MODEL: "gemini-flash-latest",
  MAX_OUTPUT_TOKENS: 4096,
  TEMPERATURE: 0.7,
  TITLE_MAX_TOKENS: 600,
};

export const ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_API_KEY: "MISSING_API_KEY",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  USER_QUOTA_EXCEEDED: "You have 0 AI tokens remaining. Please wait 24 hours.",
  MODEL_NOT_FOUND: "MODEL_NOT_FOUND",
  CONTENT_BLOCKED: "CONTENT_BLOCKED",
  EMPTY_RESPONSE: "EMPTY_RESPONSE",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
